universe = vanilla
executable = condor_run.sh
error = $(Cluster).$(Process).condor_mfcl.err
log = $(Cluster).$(Process).condor_mfcl.log
output = $(Cluster).$(Process).condor_mfcl.out
requirements = (OpSys == "LINUX") && (Machine != "nouofpcalc02.corp.spc.int")
rank = (-SlotID * Mips)
request_memory = 6000
request_disk = 5500000
when_to_transfer_output = ON_EXIT_OR_EVICT
should_transfer_files = YES
transfer_input_files = Start.tar.gz
transfer_output_files = End.tar.gz
queue
